apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    project: bookmyshow
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    project: bookmyshow

